version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
