version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_ORIGIN_PRODUCTION: ${ALLOWED_ORIGIN_PRODUCTION}
      ALLOWED_ORIGIN_DEVELOPMENT: ${ALLOWED_ORIGIN_DEVELOPMENT}
      LOG_LEVEL: ${LOG_LEVEL}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_URL: ${OPENROUTER_URL}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
